### ISSUE TITLE
Remove build code after test

### ISSUE THREAD

**Issue by sarina** [sarina/gh-scripting#1]

**Comment by jmakowski1123** [comment]
assign me

**Comment by jmakowski1123** [comment]
assign me

**Comment by nedbat** [comment]
hi, I don't want to own this issue.

**Comment by sarina** [comment]
@nedbat  yep I don't know how but I skipped a condition! I totally wrote it... somewhere. Try now? with and without an "assign me" at the beginning?

**Comment by nedbat** [comment]
Hi, I'm interested, but won't own this.

**Comment by nedbat** [comment]
assign me on second thought!

**Comment by nedbat** [comment]
:+1: looks like it works.
